### ISSUE TITLE
[TODO] README

### ISSUE THREAD

**Issue by zhaohanson1** [zhaohanson1/word_tools#38]
I forgot how this project works. A good exercise would be to explore this project again and document everything.
- [ ] How to install
- [ ] How to run
- [ ] How to deploy
- [ ] Project structure

GLHF :)
